### ISSUE TITLE
Alerts?

### ISSUE THREAD

**Issue by aoraion** [cmsart/Satoshi#2]
Hello! 

This is just what I’ve been looking for to add to my discord channel. Any chance of adding alerts? I first found the coin market bot, and liked the alert setting ability, but it more interested in real-time data from both binance and Bittrex. 

Thanks!

**Comment by aoraion** [comment]
Again, adding alerts would be fantastic. I currently use [CoinMarketBot](https://github.com/kodycode/CoinMarketBot) for alerts, but it's only pulling prices from CoinMarketCap.com, where I would prefer pulling prices from the exchanges themselves. You help is much appreciated!

**Comment by cmsart** [comment]
Hey, sorry I missed your first comment.

Unfortunately, the way I designed the bot prohibits me from doing real-time alerts like how you described. Adding that functionality would require a pretty major overhaul of the code, and while I do like the idea and may work on implementing it in the future, it's not something I plan to develop at the moment. Thanks for the suggestion!

**Comment by aoraion** [comment]
I understand. If I were to host the bot, would I be able to increase the
amount of alerts to as many as I want? I post a lot of calls (about 35 at a
time).

**Comment by aoraion** [comment]
Also, I’d be happy to invite you to my discord group if you want to see how
I’m using your bot :)
