### ISSUE TITLE
USD price is possible ?

### ISSUE THREAD

**Issue by comefrombeginning** [cmsart/Satoshi#3]
Hello can we have some reference about usdt price

Thanks

**Comment by cmsart** [comment]
This is available already for Bittrex and Binance. Use the `+coin <currency pair> <exchange>` command like so:

`+coin USDT_ETH bittrex`
`+coin TUSD_BCH binance`

This works for all USD/crypto pairs. You can also type `+help` if the bot is in your server for more info.
